name: Dart CI

on: push
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

env:
  flutter_channel: 'master' # or: 'dev' or 'beta'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: subosito/flutter-action@v1

    - uses: actions/setup-java@v1


    - run: flutter pub get
    # - run: flutter test

    - name: build APK
      run: flutter build apk

    - name: upload APK
      uses: actions/upload-artifact@v1
      with:
        name: apk 